workflows:
    build-firebase:
        name: Build and publish to Firebase
        max_build_duration: 120
        instance_type: mac_mini_m1
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: 'release_DanyloBurliai'
                  include: true
        environment:
            groups:
                - firebase_credentials
            ios_signing:
                distribution_type: development
                bundle_identifier: ua.edu.ukma.apple-env.burliai.CatsViewer
        scripts:
            - name: Export IPA
              script: sh ExportIPA.sh
        artifacts:
            - output/CatsViewer.ipa
